load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "memento_pattern",
    srcs = ["memento_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "memento_pattern_undo_redo",
    srcs = ["memento_pattern_undo_redo.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
