load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "dynamic_decorator_pattern",
    srcs = ["dynamic_decorator_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "static_decorator_pattern",
    srcs = ["static_decorator_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
