load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "composite_pattern",
    srcs = ["composite_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "neural_network",
    srcs = ["neural_network.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "array_backed_properties",
    srcs = ["array_backed_properties.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
