load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "dynamic_strategy_pattern",
    srcs = ["dynamic_strategy_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "static_strategy_pattern",
    srcs = ["static_strategy_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
