load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "adapter_pattern",
    srcs = ["adapter_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
