load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "factory_pattern",
    srcs = ["factory_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "abstract_factory",
    srcs = ["abstract_factory.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
