load("@rules_cc//cc:defs.bzl",  "cc_test")

cc_test(
  name = "single_responsibility_principle",
  srcs = ["single_responsibility_principle.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "open-closed_principle",
  srcs = ["open-closed_principle.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "liskov_substitution_principle",
  srcs = ["liskov_substitution_principle.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)
