load("@rules_cc//cc:defs.bzl",  "cc_test")

cc_test(
  name = "single_responsibility_principle_unit_tests",
  srcs = ["single_responsibility_principle.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)
