#ifndef DESIGN_PATTERNS_SOLID_SINGLE_RESPONSIBILITY_PRINCIPLE_HPP
#define DESIGN_PATTERNS_SOLID_SINGLE_RESPONSIBILITY_PRINCIPLE_HPP

#include <iostream>

namespace solid
{

class SingleResponsibilityPrinciple
{

};

}  // namespace solid

#endif  // DESIGN_PATTERNS_SOLID_SINGLE_RESPONSIBILITY_PRINCIPLE_HPP
