load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "template_method",
    srcs = ["template_method.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
