load("@rules_cc//cc:defs.bzl",  "cc_test")

cc_test(
  name = "iterator_pattern",
  srcs = ["iterator_pattern.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "binary_tree_iterator",
  srcs = ["binary_tree_iterator.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)
