load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "chain_of_responsibility_pattern",
    srcs = ["chain_of_responsibility_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
