load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "pimpl_idiom",
    srcs = ["pimpl_idiom.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "shrink_wrapped_pimpl",
    srcs = ["shrink_wrapped_pimpl.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "bridge_pattern",
    srcs = ["bridge_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
