load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "creational_patterns_test",
    srcs = glob(["*.cpp"]),
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
