load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "state_pattern",
    srcs = ["state_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "handmade_state_machine",
    srcs = ["handmade_state_machine.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
