load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "builder_pattern",
    srcs = ["builder_pattern_example_with_html_code_creation.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "groovy_builder_pattern",
    srcs = ["builder_pattern_example_groovy_style_builder.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
