load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "interpreter_pattern",
    srcs = ["interpreter_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
