load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "command_pattern",
    srcs = ["command_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "composite_pattern",
    srcs = ["composite_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
