load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "all_principles",
    srcs = glob(["*.cpp"]),
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "single_responsibility_principle",
    srcs = ["single_responsibility_principle.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "open-closed_principle",
    srcs = ["open-closed_principle.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "liskov_substitution_principle",
    srcs = ["liskov_substitution_principle.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "interface_segregation_principle",
    srcs = ["interface_segregation_principle.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "dependency_inversion_principle",
    srcs = ["dependency_inversion_principle.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
