#load("@rules_cc//cc:defs.bzl",  "cc_test", "cc_library")
#
#cc_library(
#  name = "builder_pattern_using_three_builders",
#  hdrs = glob(["*.hpp"]),
#)
#
#cc_test(
#  name = "builder_pattern_using_three_builders_test",
#  srcs = glob(["*_test.cpp"]),
#  deps = [
#    "builder_pattern_using_three_builders",
#    "@googletest//:gtest",
#    "@googletest//:gtest_main",
#  ]
#)
