load("@rules_cc//cc:defs.bzl",  "cc_test")

cc_test(
  name = "proxy_pattern",
  srcs = ["proxy_pattern.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "property_proxy_pattern",
  srcs = ["property_proxy_pattern.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)
