load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "intrusive_visitor_pattern",
    srcs = ["intrusive_visitor_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "reflective_visitor_pattern",
    srcs = ["reflective_visitor_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "classic_visitor_pattern",
    srcs = ["classic_visitor_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "acyclic_visitor_pattern",
    srcs = ["acyclic_visitor_pattern.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "multimethods",
    srcs = ["multimethods.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "std_variant_and_visit",
    srcs = ["std_variant_and_visit.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
