load("@rules_cc//cc:defs.bzl",  "cc_test")

cc_test(
  name = "intrusive_visitor_pattern",
  srcs = ["intrusive_visitor_pattern.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)
